// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public partial class TestAddress
    {
        public TestAddress()
        {
            TestPerson = new HashSet<TestPerson>();
        }

        public decimal Addressid { get; set; }
        public string Streetadress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }

        public virtual ICollection<TestPerson> TestPerson { get; set; }
    }
}