// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public partial class TestPerson
    {
        public decimal Personid { get; set; }
        public string Name { get; set; }
        public decimal? Age { get; set; }
        public decimal? EmailId { get; set; }
        public decimal? AddressId { get; set; }

        public virtual TestAddress Address { get; set; }
        public virtual TestEmail Email { get; set; }
    }
}