// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain
{
    public partial class TestEmail
    {
        public TestEmail()
        {
            TestPerson = new HashSet<TestPerson>();
        }

        public decimal Emailid { get; set; }
        public string Emailadress { get; set; }

        public virtual ICollection<TestPerson> TestPerson { get; set; }
    }
}